### ISSUE TITLE
Question about the sample column of the single cell object

### ISSUE THREAD

**Issue by ChrisTzaferis** [nkoneill/mMuSiC#1]
Hello and thank you for developing this useful tool! I have one question regarding the tutorial for the basic analysis. More particularly, I wonder if it can be executed when the single cell object contains only measurements from one condition e.g. 'healthy'?

**Comment by nkoneill** [comment]
Hello! Thank you for the question.
We did not test this during our validation and I cannot be sure how accurate the results would be if you deconvoluted a disease condition using a healthy control reference. It is possible that our program, modifying MuSiC's weighing scheme to reduce the weight of genes that are differentially captured between reference and control, would compensate for this to a degree.

However the package that DeTREM is based off of, MuSiC, has a new version purported to do exactly what you describe:
https://xuranw.github.io/MuSiC/articles/pages/MuSiC2.html
I would recommend giving that a try!

**Comment by ChrisTzaferis** [comment]
Thank you very much for your quick reply and the suggestion! Indeed MuSiC2 could help me in the analysis I want to perform!
