### ISSUE TITLE
r.squared.full values

### ISSUE THREAD

**Issue by gevro** [nkoneill/mMuSiC#3]
Hi, What are reasonable r.squared.full values for deTREM? Is this a value that should serve as a QC to assess if the analysis worked well? Thanks

**Comment by nkoneill** [comment]
![missingness](https://github.com/nkoneill/DeTREM/assets/2753185/4650f7e9-b788-493f-b887-9b244693fca6)
I have sometimes used 'missingness', or the fraction of zero estimates, as a QC measurement. Here I have plotted it against the mean R2 value for some of my results. With this small sample size they appear to be uncorrelated. Both values should be reasonable QC metrics. The R2 values vary wildly based on how many cell-types I have included, so I could not give you a reasonable range estimate.
This should not be dissimilar from MuSiC, so you see discussion of R2 value QC in their GitHub it would also be relevant here.

**Comment by gevro** [comment]
Thanks!
